### ISSUE TITLE
State of the project?

### ISSUE THREAD

**Issue by freekvh** [ligee/kotlin-jupyter#14]
Hi ligee, thanx for this project! To me there is nothing like a notebook for learning and documenting my forays in a new programming language!

I was wondering, what is the status of this project? I just got the kernel running on Jupyter on Solus Linux without any problems but I noticed autocompletion is not working for example. Do you consider this project well maintained? Is it safe for me to try out this kernel without running into bugs that I might consider Kotlins' but are in fact this notebook kernels' bugs?

**Comment by zstauber** [comment]
Yes, thank you from me also, ligee.  I certainly hope this project can be active again.  I only learned about Jupyter Notebooks a week ago when I installed an updated ArcGIS Pro, and it came with it, and now I have seen a presentation on them from a federal agency.  I think the use and knowledge of them is just now becoming common.  Kotlin is a promising language, and I hope it can be integrated with Jupyter Notebooks.

**Comment by apatrida** [comment]
This project acted as a demonstration of Kotlin scripting being integrated into something else, I'm not sure if @ligee has plans above that or not.  I keep it up to date for recent Kotlin changes.  For auto-completion it would need a language server which is possible, and anyone who wants to tackle that surely is welcome.  You can look at the Kotlin web example that has a language server for ideas of how that might work.  PR's welcome!

**Comment by apatrida** [comment]
I'm closing the issue since it is a question, and not really an issue report.  You are welcome to add feature requests as issues each as a separate item, and we can see who might be interested in developing those.  In terms of project quality, whatever Kotlin Script supports, this supports and any bugs would be in the integration between the Jupyter system and the calling of the script engine, but that is unlikely unless Jupyter changes their protocol or uses something in the old protocol that becomes mandatory that used to be optional.
